export default function Page() {
  return (
    <main className="space-y-10">
      <h1 className="text-3xl font-bold">SSG (Static Site Generation)</h1>

      <section>
        <h2 className="text-xl font-semibold">What is Static Site Generation?</h2>
        <p className="text-gray-600 mt-2">
          Static Site Generation (SSG) is a method where web pages are created at build time, not when users visit them. During the build process, Next.js generates HTML files for each page and saves them. When users visit your site, these pre-built files are served instantly, making your site extremely fast.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold">How SSG Works</h2>
        <div className="bg-blue-50 p-4 rounded-lg">
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="bg-blue-100 text-blue-800 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold">1</div>
              <div>
                <h3 className="font-semibold">Build Time</h3>
                <p className="text-gray-600 text-sm">Next.js runs your components and generates HTML files for each page.</p>
              </div>
            </div>
            <div className="flex items-start space-x-3">
              <div className="bg-blue-100 text-blue-800 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold">2</div>
              <div>
                <h3 className="font-semibold">Save Static Files</h3>
                <p className="text-gray-600 text-sm">Generated HTML, CSS, and JavaScript are saved as static files.</p>
              </div>
            </div>
            <div className="flex items-start space-x-3">
              <div className="bg-blue-100 text-blue-800 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold">3</div>
              <div>
                <h3 className="font-semibold">Deploy to CDN</h3>
                <p className="text-gray-600 text-sm">Files are uploaded to a Content Delivery Network (CDN) for fast global delivery.</p>
              </div>
            </div>
            <div className="flex items-start space-x-3">
              <div className="bg-blue-100 text-blue-800 rounded-full w-8 h-8 flex items-center justify-center text-sm font-bold">4</div>
              <div>
                <h3 className="font-semibold">Instant Delivery</h3>
                <p className="text-gray-600 text-sm">Users get pre-built pages instantly from the nearest CDN location.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold">SSG in Next.js</h2>
        <p className="text-gray-600 mt-2">
          In Next.js App Router, pages are statically generated by default if they don't use dynamic functions. You can explicitly mark pages for static generation.
        </p>
        <div className="bg-green-50 p-4 rounded-lg">
          <h3 className="font-semibold mb-2">Static Page Example</h3>
          <div className="bg-white p-3 rounded font-mono text-sm">
            <pre>{`app/about/page.tsx:

export default function AboutPage() {
  return (
    <div>
      <h1>About Us</h1>
      <p>This page is generated at build time.</p>
      <p>Last updated: {new Date().toLocaleDateString()}</p>
    </div>
  );
}`}</pre>
          </div>
          <p className="text-gray-600 text-sm mt-2">
            This page will be generated once during build and served as a static HTML file.
          </p>
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold">Dynamic Data in SSG</h2>
        <p className="text-gray-600 mt-2">
          You can fetch data at build time using <code className="bg-gray-100 px-1 rounded">generateStaticParams</code> for dynamic routes.
        </p>
        <div className="bg-purple-50 p-4 rounded-lg">
          <h3 className="font-semibold mb-2">Dynamic Route with Static Generation</h3>
          <div className="bg-white p-3 rounded font-mono text-sm">
            <pre>{`app/blog/[slug]/page.tsx:

export async function generateStaticParams() {
  const posts = await fetch('https://api.example.com/posts')
    .then(res => res.json());

  return posts.map((post) => ({
    slug: post.slug,
  }));
}

export default async function BlogPost({
  params
}: {
  params: { slug: string }
}) {
  const post = await fetch(\`https://api.example.com/posts/\${params.slug}\`)
    .then(res => res.json());

  return (
    <article>
      <h1>{post.title}</h1>
      <p>{post.content}</p>
    </article>
  );
}`}</pre>
          </div>
          <p className="text-gray-600 text-sm mt-2">
            <code className="bg-gray-100 px-1 rounded">generateStaticParams</code> tells Next.js which pages to generate at build time.
          </p>
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold">Benefits of SSG</h2>
        <div className="grid md:grid-cols-2 gap-4">
          <div className="border rounded-lg p-4">
            <h3 className="font-semibold text-green-600">Performance</h3>
            <ul className="list-disc ml-4 mt-2 text-sm text-gray-600 space-y-1">
              <li>Fastest possible load times</li>
              <li>Instant page delivery</li>
              <li>Global CDN distribution</li>
              <li>No server processing per request</li>
            </ul>
          </div>
          <div className="border rounded-lg p-4">
            <h3 className="font-semibold text-blue-600">SEO</h3>
            <ul className="list-disc ml-4 mt-2 text-sm text-gray-600 space-y-1">
              <li>Perfect for search engines</li>
              <li>Full content available</li>
              <li>Social media friendly</li>
              <li>Fast indexing</li>
            </ul>
          </div>
          <div className="border rounded-lg p-4">
            <h3 className="font-semibold text-purple-600">Reliability</h3>
            <ul className="list-disc ml-4 mt-2 text-sm text-gray-600 space-y-1">
              <li>Works without databases</li>
              <li>No runtime errors</li>
              <li>Easy deployment</li>
              <li>Version controlled</li>
            </ul>
          </div>
          <div className="border rounded-lg p-4">
            <h3 className="font-semibold text-orange-600">Cost</h3>
            <ul className="list-disc ml-4 mt-2 text-sm text-gray-600 space-y-1">
              <li>Cheap hosting (just static files)</li>
              <li>No server costs</li>
              <li>Scales infinitely</li>
              <li>Low maintenance</li>
            </ul>
          </div>
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold">SSG vs SSR vs CSR</h2>
        <div className="overflow-x-auto">
          <table className="min-w-full border-collapse border border-gray-300">
            <thead>
              <tr className="bg-gray-50">
                <th className="border border-gray-300 px-4 py-2 text-left">Aspect</th>
                <th className="border border-gray-300 px-4 py-2 text-left">SSG</th>
                <th className="border border-gray-300 px-4 py-2 text-left">SSR</th>
                <th className="border border-gray-300 px-4 py-2 text-left">CSR</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border border-gray-300 px-4 py-2 font-semibold">When Generated</td>
                <td className="border border-gray-300 px-4 py-2">Build time</td>
                <td className="border border-gray-300 px-4 py-2">Request time</td>
                <td className="border border-gray-300 px-4 py-2">Client time</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-4 py-2 font-semibold">Performance</td>
                <td className="border border-gray-300 px-4 py-2">Fastest</td>
                <td className="border border-gray-300 px-4 py-2">Fast</td>
                <td className="border border-gray-300 px-4 py-2">Slowest</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-4 py-2 font-semibold">SEO</td>
                <td className="border border-gray-300 px-4 py-2">Excellent</td>
                <td className="border border-gray-300 px-4 py-2">Good</td>
                <td className="border border-gray-300 px-4 py-2">Poor</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-4 py-2 font-semibold">Real-time Data</td>
                <td className="border border-gray-300 px-4 py-2">Limited</td>
                <td className="border border-gray-300 px-4 py-2">Good</td>
                <td className="border border-gray-300 px-4 py-2">Excellent</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold">When to Use SSG</h2>
        <ul className="list-disc ml-6 mt-2 text-gray-600 space-y-1">
          <li><strong>Marketing Sites:</strong> Company websites, landing pages</li>
          <li><strong>Blogs:</strong> Articles, documentation, news sites</li>
          <li><strong>E-commerce:</strong> Product catalogs, category pages</li>
          <li><strong>Portfolio Sites:</strong> Personal websites, case studies</li>
          <li><strong>Content-Heavy Sites:</strong> Where content doesn't change frequently</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold">SSG Limitations</h2>
        <div className="bg-yellow-50 p-4 rounded-lg">
          <ul className="list-disc ml-6 text-gray-700 space-y-1">
            <li><strong>Build Time:</strong> Large sites can take long to build</li>
            <li><strong>Real-time Data:</strong> Can't show live data without client-side updates</li>
            <li><strong>Storage:</strong> Many pages = many static files</li>
            <li><strong>Dynamic Content:</strong> User-specific content is challenging</li>
            <li><strong>Updates:</strong> Content changes require rebuild and redeploy</li>
          </ul>
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold">Incremental Static Regeneration (ISR)</h2>
        <p className="text-gray-600 mt-2">
          ISR combines SSG with the ability to update static pages after they've been built. Pages can be regenerated in the background when needed.
        </p>
        <div className="bg-orange-50 p-4 rounded-lg">
          <div className="bg-white p-3 rounded font-mono text-sm">
            <pre>{`export const revalidate = 3600; // Regenerate every hour

export default async function BlogPost({ params }) {
  const post = await fetchBlogPost(params.slug);
  return <article>{/* post content */}</article>;
}`}</pre>
          </div>
          <p className="text-gray-600 text-sm mt-2">
            ISR gives you the speed of SSG with the freshness of SSR.
          </p>
        </div>
      </section>

      <section className="border-l-4 border-black pl-4">
        <h2 className="text-lg font-semibold">Key Takeaway</h2>
        <p className="text-gray-600">
          Static Site Generation creates pages at build time for maximum performance and SEO. It's perfect for content that doesn't change frequently and sites that need to load instantly. While it has limitations with real-time data, techniques like ISR help bridge that gap.
        </p>
      </section>
    </main>
  );
}